Import the modules

In [1]:
#imports
#numpy,pandas,scipy,math,mathplotlib
import numpy as np
import pandas as pd
import scipy
from math import sqrt
import matplotlib.pyplot as plt

#estimators
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier

#model metrics
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

#cross validation
from sklearn.model_selection import train_test_split

Import the data

In [5]:
#data
rawData = pd.read_csv('default of credit card clients.csv', header=1)
del rawData ['ID']
rawData.rename(columns = {'default payment next month':'default'}, inplace=True)
rawData.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57     -1      0     -1      0   

   PAY_5   ...     BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -2   ...             0          0          0         0       689   
1      0   ...          3272       3455       3261         0      1000   
2      0   ...         14331      14948      15549      1518      1500   
3      0   ...         28314      28959      29547      2000      2019   
4      0   ...         20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default  
0         0         0         0         0        1  
1      1000      1000         0      2000        1  
2      1000      1000      1000      5000        0  
3      1200      1100      1069      1000        0  
4     10000      9000       689       679        0  

[5 rows x 24 columns]

In [6]:
rawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
LIMIT_BAL    30000 non-null int64
SEX          30000 non-null int64
EDUCATION    30000 non-null int64
MARRIAGE     30000 non-null int64
AGE          30000 non-null int64
PAY_0        30000 non-null int64
PAY_2        30000 non-null int64
PAY_3        30000 non-null int64
PAY_4        30000 non-null int64
PAY_5        30000 non-null int64
PAY_6        30000 non-null int64
BILL_AMT1    30000 non-null int64
BILL_AMT2    30000 non-null int64
BILL_AMT3    30000 non-null int64
BILL_AMT4    30000 non-null int64
BILL_AMT5    30000 non-null int64
BILL_AMT6    30000 non-null int64
PAY_AMT1     30000 non-null int64
PAY_AMT2     30000 non-null int64
PAY_AMT3     30000 non-null int64
PAY_AMT4     30000 non-null int64
PAY_AMT5     30000 non-null int64
PAY_AMT6     30000 non-null int64
default      30000 non-null int64
dtypes: int64(24)
memory usage: 5.5 MB


Select the features

In [76]:
#features
features = rawData.iloc[:,1:23]
print('Summary of feature sample')
features.head()

Summary of feature sample


SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  PAY_6  \
0    2          2         1   24      2      2     -1     -1     -2     -2   
1    2          2         2   26     -1      2      0      0      0      2   
2    2          2         2   34      0      0      0      0      0      0   
3    2          2         1   37      0      0      0      0      0      0   
4    1          2         1   57     -1      0     -1      0      0      0   

     ...     BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0    ...           689          0          0          0         0       689   
1    ...          2682       3272       3455       3261         0      1000   
2    ...         13559      14331      14948      15549      1518      1500   
3    ...         49291      28314      28959      29547      2000      2019   
4    ...         35835      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0         0         0         0         0  
1      1000      1000         0      2000  
2      1000      1000      1000      5000  
3      1200      1100      1069      1000  
4     10000      9000       689       679  

[5 rows x 22 columns]

Select the Dependent Variable

In [77]:
#dependent variable
depVar = rawData['default']

Establish the training set for the feature space

In [79]:
#Training Set (Feature Space: X Training)
X_train = (features[: 30000])
X_train.head()

SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  PAY_6  \
0    2          2         1   24      2      2     -1     -1     -2     -2   
1    2          2         2   26     -1      2      0      0      0      2   
2    2          2         2   34      0      0      0      0      0      0   
3    2          2         1   37      0      0      0      0      0      0   
4    1          2         1   57     -1      0     -1      0      0      0   

     ...     BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0    ...           689          0          0          0         0       689   
1    ...          2682       3272       3455       3261         0      1000   
2    ...         13559      14331      14948      15549      1518      1500   
3    ...         49291      28314      28959      29547      2000      2019   
4    ...         35835      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0         0         0         0         0  
1      1000      1000         0      2000  
2      1000      1000      1000      5000  
3      1200      1100      1069      1000  
4     10000      9000       689       679  

[5 rows x 22 columns]

Establish the training set for the dependent variable (number of rows
must match the X-training set)

In [80]:
#Dependent Variable Training Set (y Training)
y_train = depVar[: 30000]
y_train_count = len(y_train.index)
print('The number of observations in the Y training set are:',str(y_train_count))
y_train.head()

The number of observations in the Y training set are: 30000


0    1
1    1
2    0
3    0
4    0
Name: default, dtype: int64

Establish the testing set for the X-Variables or feature space

In [81]:
#Testing Set (X Testing)
X_test = features[-9000:]
X_test_count = len(X_test.index)
print('The number of observations in the feature testing set is:',str(X_test_count))
print(X_test.head())

The number of observations in the feature testing set is: 9000
       SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  \
21000    1          2         1   36      1     -1     -1     -1      0   
21001    1          3         1   40      2      0      0      0      0   
21002    1          2         1   37      0      0      0      0      0   
21003    1          2         2   32      2      0      0      0     -2   
21004    1          2         2   32      2      0      0      0      0   

       PAY_6    ...     BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
21000      0    ...             0       1170        780          0       780   
21001      0    ...        188411     191291     189029     192023     10000   
21002      0    ...         21557      23186      14117      15797      3203   
21003     -2    ...         81890          0          0          0      7600   
21004      2    ...         67253      67352      74448      72928      3000   

     

Establish Ground truth

In [82]:
#Ground Truth (y_test) 
y_test = depVar[-9000:]
y_test_count = len(y_test.index)
print('The number of observations in the Y training set are:',str(y_test_count))
y_test.head()

The number of observations in the Y training set are: 9000


21000    0
21001    1
21002    0
21003    1
21004    1
Name: default, dtype: int64

Cross Validation

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train)

Doublecheck that split was made using shape function

In [84]:
X_train.shape, X_test.shape

((22500, 22), (7500, 22))

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train)
X_train.shape, X_test.shape

((16875, 22), (5625, 22))

Sci-Kit Learn (linear_model Estimator Object used to access Linear Regression algorithm from the sklearn base)

In [86]:
from sklearn.linear_model import LogisticRegression

Tuning Parameters and Model Definition
model = LinearRegression(parameters go here)

In [87]:
model = LogisticRegression(n_jobs=10)

Building the Models and Choosing the Right Model

Establish variables to use for defining each model.

In [88]:
#Models
modelSVC = SVC()
modelRF = RandomForestClassifier()
modelLR = LogisticRegression()
modelLDA = LinearDiscriminantAnalysis()
modelKNN = KNeighborsClassifier()

While not mandatory it is a good idea to establish a variable specifically for features to control what is used for training.

In [89]:
#features
features = rawData.iloc[:,1:23]
print('Summary of feature sample')
features.head()

Summary of feature sample


SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  PAY_6  \
0    2          2         1   24      2      2     -1     -1     -2     -2   
1    2          2         2   26     -1      2      0      0      0      2   
2    2          2         2   34      0      0      0      0      0      0   
3    2          2         1   37      0      0      0      0      0      0   
4    1          2         1   57     -1      0     -1      0      0      0   

     ...     BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0    ...           689          0          0          0         0       689   
1    ...          2682       3272       3455       3261         0      1000   
2    ...         13559      14331      14948      15549      1518      1500   
3    ...         49291      28314      28959      29547      2000      2019   
4    ...         35835      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0         0         0         0         0  
1      1000      1000         0      2000  
2      1000      1000      1000      5000  
3      1200      1100      1069      1000  
4     10000      9000       689       679  

[5 rows x 22 columns]

Validate correct column being used for dependent variable

In [90]:
#dependent variable
print(depVar)

0        1
1        1
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       1
14       0
15       0
16       1
17       0
18       0
19       0
20       0
21       1
22       1
23       1
24       0
25       0
26       1
27       0
28       0
29       0
        ..
29970    0
29971    0
29972    0
29973    1
29974    1
29975    0
29976    1
29977    0
29978    0
29979    0
29980    0
29981    0
29982    1
29983    0
29984    0
29985    0
29986    0
29987    0
29988    0
29989    0
29990    0
29991    1
29992    0
29993    0
29994    1
29995    0
29996    0
29997    1
29998    1
29999    1
Name: default, Length: 30000, dtype: int64


Choosing the Right Model
Pass training data to the model variables created above (similar to train function from caret pkg in R).

In [91]:
from sklearn.model_selection import cross_val_score

Pass each trained model and the training sets to the function to obtain training score.
These values correspond to the the following:
1st value:  The score array for test scores on each cv split. (Higher is an indicator of a better performing model)
2nd value: The time for fitting the estimator on the train set for each cv split.
3rd Value:  The time for scoring the estimator on the test set for each cv split. 

In [92]:
#Model Fitting
modelRF.fit(X_train,y_train)
print(cross_val_score(modelRF, X_train, y_train))
modelRF.score(X_train,y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


[0.7952364  0.79182222 0.8012091 ]


0.9755851851851852

In [93]:
modelSVC.fit(X_train,y_train)
print(cross_val_score(modelSVC, X_train, y_train)) 
modelSVC.score(X_train,y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change fro

[0.77355137 0.77386667 0.77435989]


0.9893333333333333

In [94]:
modelLR.fit(X_train,y_train)
print(cross_val_score(modelLR, X_train, y_train)) 
modelLR.score(X_train,y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be change

[0.77248489 0.77226667 0.79534139]


0.7726814814814815

In [95]:
modelLDA.fit(X_train,y_train)
print(cross_val_score(modelLDA, X_train, y_train)) 
modelLDA.score(X_train,y_train)

[0.81283327 0.81048889 0.80636558]


/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


0.8101925925925926

In [96]:
modelKNN.fit(X_train,y_train)
print(cross_val_score(modelKNN, X_train, y_train)) 
modelKNN.score(X_train,y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


[0.75204408 0.74613333 0.75124467]


0.8180740740740741

Make Predictions

In [97]:
#Make Predictions
predictions = modelRF.predict(X_test)
predAccuracy = accuracy_score(y_test,predictions)
print('Accuracy: %.3f' % predAccuracy)

Accuracy: 0.808


In [98]:
#Make Predictions
predictions = modelSVC.predict(X_test)
predAccuracy = accuracy_score(y_test,predictions)
print('Accuracy: %.3f' % predAccuracy)

Accuracy: 0.788
